### ISSUE TITLE
AUTHORS.txt

### ISSUE THREAD

**Issue by FGDATA** [ElGaton/festival-flightgear-november-2015#1]
Hi Elgaton

I would like you to consider creating an AUTHORS.txt file, to acknowledge, sort to speak, the collaborators -- and maybe list the files they contributed to (?)

Thanks for all this record keeping work

IH-COL

**Comment by AlessandroMenti** [comment]
Hi IH-COL,
I agree on keeping track of individual authorship - I think, however, it would make more sense to include appropriate GPL notices in individual files, as, once the Festival is finished, I'm going to send them upstream for inclusion. Could that be a good solution?

**Comment by IAHM-COL** [comment]
sure.
