### ISSUE TITLE
LOWI custom scenery and osm2city

### ISSUE THREAD

**Issue by onox** [ElGaton/festival-flightgear-november-2015#3]
You might want to mention the scenery for LOWI on the [forum](http://forum.flightgear.org/viewtopic.php?f=10&t=24534):
- osm2city at https://dl.dropboxusercontent.com/u/24846517/fg/osm2city/LOWI_OSM_buildings_20140928.tgz (should contain the directory `Objects/e010n40/e011n47`) (found the link via the [forum](http://forum.flightgear.org/viewtopic.php?f=5&t=19625))
- LOWI custom scenery at https://github.com/FGMEMBERS-SCENERY/LOWI-fg-CustomScenery

**Comment by AlessandroMenti** [comment]
Fixed. Thanks!
